name: App Platform Java Compile

on:
  push:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+.x'  # 匹配 x.x.x 格式且最后一位为 x（如 1.2.x、22.1.x）
    paths:
      - 'app-builder/**'
      - '!app-builder/fel/python/**'
      - 'app-engine/**'
      - '!app-engine/frontend/**'
      - 'app-image/**'
      - 'app-knowledge/**'
      - 'carver/**'
      - 'common/**'
      - 'store/**'
  pull_request:
    branches:
      - 'main'
      - '[0-9]+.[0-9]+.x'  # 匹配 x.x.x 格式且最后一位为 x（如 1.2.x、22.1.x）
    paths:
      - 'app-builder/**'
      - '!app-builder/fel/python/**'
      - 'app-engine/**'
      - '!app-engine/frontend/**'
      - 'app-image/**'
      - 'app-knowledge/**'
      - 'carver/**'
      - 'common/**'
      - 'store/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install